#!/usr/bin/env python3
"""Compose the lockup from the emblem module.

The shipped SVG inlines the emblem so it still draws when a tool will not
follow an external reference. Edit logo/mark-desktop.svg, then run this.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARK = ROOT / "logo" / "mark-desktop.svg"
LOCKUP = ROOT / "logo" / "full-lockup.svg"


def extract_emblem(svg: str) -> str:
    start = svg.index('<g id="emblem"')
    depth = 0
    i = start
    while i < len(svg):
        if svg.startswith("</g>", i):
            depth -= 1
            i += 4
            if depth == 0:
                return svg[start:i]
            continue
        if svg.startswith("<g", i) and (i + 2 == len(svg) or svg[i + 2] in " \t\n>/"):
            depth += 1
            i += 2
            continue
        i += 1
    raise SystemExit("emblem group is unclosed")


def lockup_svg() -> str:
    emblem = extract_emblem(MARK.read_text())
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 700" role="img" aria-label="tiny Internet company — Pacific roots. Island heart. Quiet work.">
  <!-- Generated by logo/build_lockup.py from mark-desktop.svg. -->
  <g transform="translate(40 90) scale(0.62)">
    {emblem}
  </g>
  <g fill="#F7E5C4" text-anchor="middle" font-family="Georgia, 'Times New Roman', serif">
    <text x="1140" y="230" font-size="184">tiny</text>
    <text x="1140" y="338" font-size="70">Internet company</text>
    <text x="1140" y="420" font-size="38" font-style="italic">Pacific roots. Island heart. Quiet work.</text>
  </g>
</svg>
"""


def main() -> None:
    LOCKUP.write_text(lockup_svg())
    print(f"wrote {LOCKUP.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
