#!/usr/bin/env python3
"""Build a square transparent favicon from the emblem.

The page mark is a wide hairline drawing, so a tab icon of that file
disappears. This keeps the same paths, thickens the strokes, and fits
them in a square with no background plate.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARK = ROOT / "logo" / "mark-desktop.svg"
FAVICON = ROOT / "favicon.svg"
STROKE_SCALE = 3.4
HALO_SCALE = 5.2


def extract_emblem(svg: str) -> str:
    start = svg.index('<g id="emblem"')
    depth = 0
    i = start
    while i < len(svg):
        if svg.startswith("</g>", i):
            depth -= 1
            i += 4
            if depth == 0:
                return svg[start:i]
            continue
        if svg.startswith("<g", i) and (i + 2 == len(svg) or svg[i + 2] in " \t\n>/"):
            depth += 1
            i += 2
            continue
        i += 1
    raise SystemExit("emblem group is unclosed")


def thicken(emblem: str, scale: float) -> str:
    def wider(match: re.Match[str]) -> str:
        return f'{match.group(1)}{float(match.group(2)) * scale:.1f}'

    emblem = re.sub(r'(stroke-width=")([0-9.]+)', wider, emblem)
    return re.sub(r'(\sr=")([0-9.]+)', wider, emblem)


def favicon_svg() -> str:
    source = extract_emblem(MARK.read_text())
    emblem = (
        thicken(source, STROKE_SCALE)
        .replace('stroke="#7FAE96"', 'stroke="#246B4E"')
        .replace('stroke="#F05E50"', 'stroke="#E23D32"')
        .replace('fill="#F05E50"', 'fill="#E23D32"')
    )
    halo = thicken(source, HALO_SCALE).replace('stroke="#7FAE96"', 'stroke="#F4EFE4"').replace(
        'stroke="#F05E50"', 'stroke="#F4EFE4"'
    ).replace('fill="#F05E50"', 'fill="#F4EFE4"')
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1200">
  <!-- Generated by logo/build_favicon.py from mark-desktop.svg. Transparent. -->
  <g transform="translate(-64 320)">
    {halo}
    {emblem}
  </g>
</svg>
"""


def main() -> None:
    FAVICON.write_text(favicon_svg())
    print(f"wrote {FAVICON.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
