#!/usr/bin/env python3
"""Derive the values frame from the painted master.

The four lines live in index.html. This module owns the painted
rectangles those lines occupied, clears them, and records their centers
for values-lines.css.
"""

from __future__ import annotations

import array
import struct
import subprocess
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "ui" / "values-sign-2x.png"
FRAME = ROOT / "ui" / "values-sign-frame.webp"
PAINTED = ROOT / "ui" / "values-sign.png"
LINES_CSS = ROOT / "values-lines.css"

MASTER_W = 2460
MASTER_H = 2556

# Glyph cores on the master: x0, x1, y0, y1. Centers feed the stylesheet.
GLYPHS = [
    (985, 1720, 800, 871),
    (990, 1449, 1045, 1142),
    (1001, 1669, 1300, 1402),
    (1000, 1715, 1594, 1660),
]

# Padded bands the lettering mask is allowed to occupy. Icons sit outside them.
MASK_RECTS = [
    (930, 1780, 770, 930),
    (930, 1560, 1010, 1185),
    (960, 1760, 1265, 1445),
    (970, 1780, 1555, 1705),
]


def line_css() -> str:
    x = GLYPHS[0][0] / MASTER_W * 100
    lines = [
        "/* Generated by ui/build_values_frame.py from the painted glyph bounds. */",
        ":root {",
        f"  --values-line-x: {x:.2f}%;",
    ]
    for index, (_x0, _x1, y0, y1) in enumerate(GLYPHS, start=1):
        y = (y0 + y1) / 2 / MASTER_H * 100
        lines.append(f"  --values-line-{index}: {y:.2f}%;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _cream(r: int, g: int, b: int, a: int) -> bool:
    if a < 160 or r < 168 or g < 138 or b < 96:
        return False
    if r - b < 26 or g > r + 8 or abs(r - g) > 78:
        return False
    if b > 215 and g > 210:
        return False
    return True


def _png(rgba: bytes, width: int, height: int) -> bytes:
    buf = bytearray()
    stride = width * 4
    for y in range(height):
        buf.append(0)
        start = y * stride
        buf.extend(rgba[start : start + stride])
    comp = zlib.compress(bytes(buf), 1)

    def chunk(tag: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + tag
            + payload
            + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", comp) + chunk(b"IEND", b"")


def clear_lettering(rgba: bytearray) -> bytearray:
    width, height = MASTER_W, MASTER_H
    mask = bytearray(width * height)
    for x0, x1, y0, y1 in MASK_RECTS:
        for y in range(y0, y1):
            row = y * width
            for x in range(x0, x1):
                i = (row + x) * 4
                if _cream(rgba[i], rgba[i + 1], rgba[i + 2], rgba[i + 3]):
                    mask[row + x] = 1

    seeds = bytes(mask)
    radius = 4
    for x0, x1, y0, y1 in MASK_RECTS:
        for y in range(y0, y1):
            row = y * width
            for x in range(x0, x1):
                if seeds[row + x]:
                    continue
                hit = False
                for yy in range(max(0, y - radius), min(height, y + radius + 1)):
                    base = yy * width
                    if any(seeds[base + xx] for xx in range(max(0, x - radius), min(width, x + radius + 1))):
                        hit = True
                        break
                if hit:
                    mask[row + x] = 1

    out = bytearray(rgba)
    for y in range(height):
        row = y * width
        x = 0
        while x < width:
            if not mask[row + x]:
                x += 1
                continue
            x0 = x
            while x < width and mask[row + x]:
                x += 1
            x1 = x
            left = x0 - 1
            right = min(width - 1, x1)
            while left > 0 and mask[row + left]:
                left -= 1
            while right < width - 1 and mask[row + right]:
                right += 1
            li = (row + left) * 4
            ri = (row + right) * 4
            lr, lg, lb = out[li], out[li + 1], out[li + 2]
            rr, rg, rb = out[ri], out[ri + 1], out[ri + 2]
            span = max(1, x1 - x0)
            for step, xx in enumerate(range(x0, x1)):
                t = (step + 0.5) / span
                donor_x = max(0, left - 20 + ((xx * 5 + y * 3) % 18))
                if mask[row + donor_x]:
                    donor_x = left
                di = (row + donor_x) * 4
                oi = (row + xx) * 4
                out[oi] = (int(lr + (rr - lr) * t) + out[di]) // 2
                out[oi + 1] = (int(lg + (rg - lg) * t) + out[di + 1]) // 2
                out[oi + 2] = (int(lb + (rb - lb) * t) + out[di + 2]) // 2
                out[oi + 3] = 255
    return out


def _decode_master() -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        raw_path = Path(tmp) / "master.rgba"
        subprocess.run(
            [
                "ffmpeg", "-y", "-v", "error",
                "-i", str(MASTER),
                "-f", "rawvideo", "-pix_fmt", "rgba",
                str(raw_path),
            ],
            check=True,
        )
        raw = raw_path.read_bytes()
    expected = MASTER_W * MASTER_H * 4
    if len(raw) != expected:
        raise SystemExit(f"master decoded to {len(raw)} bytes, expected {expected}")
    return raw


def _write_frame(cleared: bytes) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        png_path = Path(tmp) / "frame.png"
        png_path.write_bytes(_png(cleared, MASTER_W, MASTER_H))
        subprocess.run(
            ["cwebp", "-q", "82", "-alpha_q", "90", "-resize", "1230", "0", str(png_path), "-o", str(FRAME)],
            check=True,
        )


def _write_painted_half() -> None:
    subprocess.run(
        [
            "ffmpeg", "-y", "-v", "error",
            "-i", str(MASTER),
            "-vf", "scale=1230:1278",
            "-pix_fmt", "rgba",
            str(PAINTED),
        ],
        check=True,
    )


def main() -> None:
    LINES_CSS.write_text(line_css())
    cleared = clear_lettering(bytearray(_decode_master()))
    _write_frame(bytes(cleared))
    _write_painted_half()
    print(f"wrote {FRAME.relative_to(ROOT)}")
    print(f"wrote {PAINTED.relative_to(ROOT)}")
    print(f"wrote {LINES_CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
